<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Public Repos 321  Last Update 8132024, 112617 AM</name>
   <tag></tag>
   <elementGuidId>b3f2723f-3817-4fea-9141-14f731d96a61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/article/div/div[2]/p[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e0929f67-c910-4136-be20-aa26caa1dc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Public Repos: 321    Last Update: 8/13/2024, 11:26:17 AM</value>
      <webElementGuid>2032d3c8-ea5f-409f-9042-fbd5667adbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[1]/section[@class=&quot;profile-section&quot;]/article[@class=&quot;profile-container&quot;]/div[@class=&quot;profile&quot;]/div[@class=&quot;profile-text&quot;]/p[6]</value>
      <webElementGuid>d7e22485-4674-4562-8d66-393f67287d85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/article/div/div[2]/p[6]</value>
      <webElementGuid>0353f89a-5964-4f53-a93f-74c1ab972629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Joined:'])[1]/following::p[1]</value>
      <webElementGuid>054f6748-1152-471f-b161-678b6b1c7f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter:'])[1]/following::p[2]</value>
      <webElementGuid>5b07f1aa-3f41-490f-b43c-dc12e8c3fc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='321']/parent::*</value>
      <webElementGuid>87abe556-76f0-4289-abc0-547068336290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]</value>
      <webElementGuid>1e43056b-9157-4c45-bfd1-e945f7aaa8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Public Repos: 321    Last Update: 8/13/2024, 11:26:17 AM' or . = 'Public Repos: 321    Last Update: 8/13/2024, 11:26:17 AM')]</value>
      <webElementGuid>069b2263-f800-4421-af6f-8f2e40abf8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
